$x = 0
$supportDirectory = join-path $env:systemdrive "\Support"
#Enable Restore point, create restore point if possible.
Try { 
     Enable-ComputerRestore -Drive $Env:systemdrive  
     $Description = "CHANGE_ME"
	 CheckPoint-Computer -Description $Description
     "Restore Point created within the last 24 hours." > $Env:systemdrive\Support\log.txt
	 $x = $x + 1
    }
Catch {
     "Failed to create Restore Point." > $Env:systemdrive\Support\log.txt
	 $x = $x + 2
      }
if (!(test-path $supportDirectory))
	{
		New-Item -ItemType Directory -Force -Path $supportDirectory
	}
if ($x = 1)
	{
		#Run DISM repairs for Windows 8 or later
		dism /online /cleanup-image /restorehealth >> $Env:systemdrive\Support\log.txt
		#Run CheckDisk repairs on a drive currently in use
		chkdsk $Env:systemdrive /I >> $Env:systemdrive\Support\log.txt
		#Run System File Checker. This tool is replaced by DISM for Windows 8 or later machines.
		sfc /scannow >> $Env:systemdrive\Support\log.txt
		#The below command re-registers modern apps for Windows 8 and Windows 10. Useful for repairing apps like Mail, Photos, CortanaUI
		Get-AppXPackage -AllUsers | Foreach {Add-AppXPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"} >> \Support\log.txt
		#Copy the CBS log generated by SFC for further inspection
		xcopy $Env:systemdrive\Windows\Logs\CBS\CBS.log $Env:systemdrive\ /Y
        Exit 0
	}
else 
	{
		Write-Host "Unable to run repairs."
        Exit 1001
	}
end if
